[package]
name = "Ascii_Rotating_Cube"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ncurses = "6.0.1"
ratatui = "0.29.0"

[[bin]]
name = "rotating_cube"
path = "src/main.rs"
